---

- name: install macvlan ifup/down scripts
  copy:
    src: "{{ item.name }}"
    dest: "/etc/sysconfig/network-scripts/{{ item.dst }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    backup: yes
  yum:
    src: "{{ item.name }}"
    state: "{{ item.name }}"
  with_items:
    - { src: ifup-macvlan, dst: ifup-macvlan, mode: 0755 }
    - { src: ifdown-macvlan, dst: ifdown-macvlan, mode: 0755 }
    - { src: ifcfg-macvlan0.example, dst: ifcfg-macvlan0.example, mode: 0644 }
  when:
    - ansible_os_family == "RedHat"