---

- name: install lxc
  yum:
    name: {{ item.name }}
    state: {{ item.state }}
  with_items:
    - { name: lxc, state: latest }
    - { name: lxc-libs, state: latest }
  when:
    - ansible_os_family == "RedHat"

- name: Update Oracle LXC Template with aarch64(rpi3) support
  copy:
    src: lxc-oracle
    dest: /usr/share/lxc/templates/lxc-oracle
    owner: root
    group: root
    mode: 0755
    backup: yes
  when:
    - ansible_os_family == "RedHat" and "{{ lxc_install }}" == true